spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://172.19.0.1:3306/taco
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    rest:
      base-path: /api
