spring:
  datasource:
    url: jdbc:postgresql://172.18.0.1:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true

server:
  port: 8180
