spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://172.18.0.1:5432/taco-cloud
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
